import type { OrchestratorQuestion as Question } from '@quiz/shared';
import { v4 as uuidv4 } from 'uuid';

const questionBank: Omit<Question, 'id'>[] = [
  {
    text: "What is the capital of Australia?",
    options: ["Sydney", "Melbourne", "Canberra", "Perth"],
    correctIndex: 2,
    category: "geography",
    difficulty: "medium",
    explanation: "Canberra was purpose-built as the capital in 1913 as a compromise between Sydney and Melbourne.",
    detailedExplanation: "When Australia federated in 1901, both Sydney and Melbourne fiercely competed to be the nation's capital. The compromise was to build an entirely new city between them. The name 'Canberra' comes from the local Ngunnawal language, meaning 'meeting place.' American architects Walter Burley Griffin and Marion Mahony Griffin won an international design competition, creating a city centered around an artificial lake. Construction began in 1913, and Parliament finally moved from Melbourne to Canberra in 1927. Today, Canberra is home to many national institutions including Parliament House, the Australian War Memorial, and the National Gallery of Australia.",
    citationUrl: "https://en.wikipedia.org/wiki/Canberra",
    citationTitle: "Wikipedia: Canberra",
  },
  {
    text: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
    correctIndex: 1,
    category: "science",
    difficulty: "easy",
    explanation: "Mars appears red due to iron oxide (rust) on its surface.",
    detailedExplanation: "Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System. Its distinctive red-orange appearance is caused by iron oxide (rust) prevalent on its surface, which led ancient civilizations to associate it with blood and war. The Romans named it after their god of war. Mars has the largest volcano in the solar system (Olympus Mons, 21.9 km tall) and the largest canyon (Valles Marineris, 4,000 km long). It has two small moons, Phobos and Deimos, and is the most explored planet after Earth, with multiple rovers including Curiosity and Perseverance currently operating on its surface.",
    citationUrl: "https://en.wikipedia.org/wiki/Mars",
    citationTitle: "Wikipedia: Mars",
  },
  {
    text: "Who painted the Mona Lisa?",
    options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Michelangelo"],
    correctIndex: 2,
    category: "arts",
    difficulty: "easy",
    explanation: "Leonardo da Vinci painted the Mona Lisa between 1503-1519.",
    detailedExplanation: "The Mona Lisa (La Gioconda in Italian) was painted by Leonardo da Vinci between 1503 and 1519. The subject is believed to be Lisa Gherardini, wife of Florentine merchant Francesco del Giocondo. The painting is renowned for its subject's enigmatic expression, the monumentality of the composition, and the subtle modeling of forms and atmospheric illusionism. Leonardo used his signature sfumato technique, creating soft transitions between colors. The painting was acquired by King Francis I of France and has been displayed at the Louvre Museum since 1797. In 1911, it was stolen by museum employee Vincenzo Peruggia and recovered two years later, an event that dramatically increased its fame.",
    citationUrl: "https://en.wikipedia.org/wiki/Mona_Lisa",
    citationTitle: "Wikipedia: Mona Lisa",
  },
  {
    text: "What is the largest ocean on Earth?",
    options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
    correctIndex: 3,
    category: "geography",
    difficulty: "easy",
    explanation: "The Pacific Ocean covers 165 million km², more than all land combined.",
    detailedExplanation: "The Pacific Ocean is the largest and deepest ocean on Earth, covering approximately 165 million square kilometers—more than all of Earth's landmass combined. It extends from the Arctic Ocean in the north to the Southern Ocean in the south, and from Asia and Australia in the west to the Americas in the east. The name 'Pacific' means 'peaceful' and was given by Portuguese explorer Ferdinand Magellan in 1521 during calm seas. The Pacific contains the Mariana Trench, where the Challenger Deep reaches 10,935 meters—the deepest known point on Earth. It also contains the Ring of Fire, a zone of frequent earthquakes and volcanic eruptions.",
    citationUrl: "https://en.wikipedia.org/wiki/Pacific_Ocean",
    citationTitle: "Wikipedia: Pacific Ocean",
  },
  {
    text: "In what year did World War II end?",
    options: ["1943", "1944", "1945", "1946"],
    correctIndex: 2,
    category: "history",
    difficulty: "medium",
    explanation: "WWII ended in 1945: Germany in May, Japan in September.",
    detailedExplanation: "World War II was the deadliest conflict in human history, lasting from 1939 to 1945 and involving over 30 countries. The war in Europe ended on May 8, 1945 (V-E Day) when Nazi Germany surrendered unconditionally to the Allied forces, following Adolf Hitler's suicide in his Berlin bunker. The war in the Pacific continued until Japan's surrender on September 2, 1945 (V-J Day), following the atomic bombings of Hiroshima (August 6) and Nagasaki (August 9). The war resulted in an estimated 70-85 million fatalities, including 6 million Jews killed in the Holocaust. Its aftermath reshaped the global political order, leading to the creation of the United Nations and the beginning of the Cold War.",
    citationUrl: "https://en.wikipedia.org/wiki/World_War_II",
    citationTitle: "Wikipedia: World War II",
  },
  {
    text: "What is the chemical symbol for gold?",
    options: ["Go", "Gd", "Au", "Ag"],
    correctIndex: 2,
    category: "science",
    difficulty: "medium",
    explanation: "Au comes from the Latin word 'aurum' meaning 'shining dawn'.",
    detailedExplanation: "Gold's chemical symbol Au comes from the Latin word 'aurum,' meaning 'shining dawn' or 'glow of sunrise.' Gold has atomic number 79 and is one of the few elements that occurs naturally in pure form. It has been valued throughout human history for its rarity, beauty, and resistance to corrosion. Gold is extremely malleable—one ounce can be beaten into a 300 square foot sheet. About 50% of all gold ever mined has been used for jewelry, 40% for investments and reserves, and 10% for industrial applications including electronics. The world's largest gold reserves are held by the United States at Fort Knox.",
    citationUrl: "https://en.wikipedia.org/wiki/Gold",
    citationTitle: "Wikipedia: Gold",
  },
  {
    text: "Which country has won the most FIFA World Cups?",
    options: ["Germany", "Argentina", "Brazil", "Italy"],
    correctIndex: 2,
    category: "sports",
    difficulty: "medium",
    explanation: "Brazil leads with 5 World Cup wins (1958, 1962, 1970, 1994, 2002).",
    detailedExplanation: "Brazil has won the FIFA World Cup a record five times: 1958 (Sweden), 1962 (Chile), 1970 (Mexico), 1994 (USA), and 2002 (South Korea/Japan). The 1970 team, featuring Pelé, is often considered the greatest football team ever assembled. Germany and Italy each have 4 wins, while Argentina has 3 (1978, 1986 with Diego Maradona's famous 'Hand of God' and 'Goal of the Century,' and 2022 with Lionel Messi). France has 2 wins (1998, 2018), and Uruguay and England each have 1. The World Cup is held every four years and is the most watched sporting event globally, with the 2022 final drawing an estimated 1.5 billion viewers.",
    citationUrl: "https://en.wikipedia.org/wiki/FIFA_World_Cup",
    citationTitle: "Wikipedia: FIFA World Cup",
  },
  {
    text: "Who wrote 'Romeo and Juliet'?",
    options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"],
    correctIndex: 1,
    category: "literature",
    difficulty: "easy",
    explanation: "Shakespeare wrote Romeo and Juliet around 1594-1596.",
    detailedExplanation: "William Shakespeare wrote Romeo and Juliet between 1594 and 1596 during the Elizabethan era. The tragedy tells of two young lovers from feuding families in Verona, Italy—the Montagues and Capulets. The play explores themes of love, fate, and the destructive nature of feuds. Shakespeare based his play on earlier Italian sources, particularly Arthur Brooke's poem 'The Tragical History of Romeus and Juliet' (1562). Romeo and Juliet has been adapted countless times for stage, film, ballet, and opera, including Franco Zeffirelli's 1968 film and Baz Luhrmann's modern 1996 version. The balcony scene remains one of the most iconic moments in Western literature.",
    citationUrl: "https://en.wikipedia.org/wiki/Romeo_and_Juliet",
    citationTitle: "Wikipedia: Romeo and Juliet",
  },
  {
    text: "What is the largest mammal in the world?",
    options: ["African Elephant", "Blue Whale", "Giraffe", "Hippopotamus"],
    correctIndex: 1,
    category: "science",
    difficulty: "easy",
    explanation: "Blue whales can reach 100 feet long and weigh 200 tons.",
    detailedExplanation: "The blue whale (Balaenoptera musculus) is not only the largest mammal but the largest animal known to have ever existed on Earth. Adults can reach lengths of up to 30 meters (100 feet) and weigh up to 200 tons. A blue whale's heart weighs about 400 pounds and is roughly the size of a small car, while its tongue can weigh as much as an elephant. Despite their enormous size, blue whales feed almost exclusively on tiny krill, consuming up to 4 tons per day during peak feeding season. They were hunted nearly to extinction in the 20th century, with an estimated 360,000 killed. Today, their population has slowly recovered to about 10,000-25,000 individuals.",
    citationUrl: "https://en.wikipedia.org/wiki/Blue_whale",
    citationTitle: "Wikipedia: Blue whale",
  },
  {
    text: "Which element has the atomic number 1?",
    options: ["Helium", "Oxygen", "Hydrogen", "Carbon"],
    correctIndex: 2,
    category: "science",
    difficulty: "easy",
    explanation: "Hydrogen has just one proton, making it the simplest element.",
    detailedExplanation: "Hydrogen is the first element on the periodic table with atomic number 1, meaning it has just one proton. It's the lightest and most abundant element in the universe, comprising about 75% of all normal matter. The name comes from Greek words meaning 'water-forming' because it produces water when burned. Hydrogen was first identified by Henry Cavendish in 1766. While rare in Earth's atmosphere, hydrogen is essential for life—it's found in water and all organic compounds. Today, hydrogen is used in petroleum refining, ammonia production, and increasingly as a clean energy source in fuel cells.",
    citationUrl: "https://en.wikipedia.org/wiki/Hydrogen",
    citationTitle: "Wikipedia: Hydrogen",
  },
  {
    text: "What is the currency of Japan?",
    options: ["Yuan", "Won", "Yen", "Ringgit"],
    correctIndex: 2,
    category: "general",
    difficulty: "easy",
    explanation: "The Japanese Yen (¥) has been Japan's official currency since 1871.",
    detailedExplanation: "The Japanese yen (円, symbol: ¥, code: JPY) has been Japan's official currency since the Meiji government established it in 1871 as part of the country's modernization. The word 'yen' means 'round' or 'circle' in Japanese. The yen is one of the world's most traded currencies and is often used as a reserve currency. Unlike many currencies, the yen uses no subdivisions in daily use—the smallest unit is 1 yen. The Bank of Japan issues paper notes in denominations of ¥1,000, ¥5,000, and ¥10,000, plus coins from ¥1 to ¥500. For context: Yuan (元) is Chinese, Won (원) is Korean, and Ringgit is Malaysian.",
    citationUrl: "https://en.wikipedia.org/wiki/Japanese_yen",
    citationTitle: "Wikipedia: Japanese yen",
  },
  {
    text: "Who was the first person to walk on the Moon?",
    options: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "Michael Collins"],
    correctIndex: 2,
    category: "history",
    difficulty: "easy",
    explanation: "Neil Armstrong stepped onto the Moon on July 20, 1969, during Apollo 11.",
    detailedExplanation: "Neil Armstrong became the first human to walk on the Moon on July 20, 1969, during NASA's Apollo 11 mission. As he stepped off the lunar module Eagle, he spoke the famous words: 'That's one small step for man, one giant leap for mankind.' Buzz Aldrin joined him on the surface about 19 minutes later, while Michael Collins remained in lunar orbit aboard the command module Columbia. The Moon landing was watched by an estimated 600 million people worldwide. Armstrong and Aldrin spent about two and a half hours on the lunar surface, collecting samples and planting the American flag. The Apollo program continued through 1972, with 12 astronauts walking on the Moon.",
    citationUrl: "https://en.wikipedia.org/wiki/Apollo_11",
    citationTitle: "Wikipedia: Apollo 11",
  },
  {
    text: "What is the tallest mountain in the world?",
    options: ["K2", "Mount Everest", "Kangchenjunga", "Lhotse"],
    correctIndex: 1,
    category: "geography",
    difficulty: "easy",
    explanation: "Mount Everest stands at 8,849 meters (29,032 feet) above sea level.",
    detailedExplanation: "Mount Everest is Earth's highest mountain above sea level, with a peak elevation of 8,849 meters (29,032 feet). Located in the Mahalangur Himal sub-range of the Himalayas, it straddles the border between Nepal (where it's called Sagarmāthā) and Tibet (where it's called Chomolungma, meaning 'Goddess Mother of the World'). The mountain was first summited on May 29, 1953, by New Zealander Edmund Hillary and Nepali Tenzing Norgay. Since then, over 6,000 people have reached the summit, though more than 300 have died attempting. The 'death zone' above 8,000 meters has oxygen levels insufficient to sustain human life for extended periods. K2 (8,611m) is the second-tallest but is considered more technically challenging to climb.",
    citationUrl: "https://en.wikipedia.org/wiki/Mount_Everest",
    citationTitle: "Wikipedia: Mount Everest",
  },
  {
    text: "Which band released the album 'Abbey Road'?",
    options: ["The Rolling Stones", "Led Zeppelin", "The Beatles", "Pink Floyd"],
    correctIndex: 2,
    category: "entertainment",
    difficulty: "medium",
    explanation: "The Beatles released Abbey Road in 1969 with its iconic crosswalk cover.",
    detailedExplanation: "Abbey Road was the eleventh studio album by The Beatles, released on September 26, 1969. Though 'Let It Be' was released later in 1970, Abbey Road was actually the last album the band recorded together. The iconic cover photograph, showing John, Ringo, Paul, and George crossing the zebra crossing outside Abbey Road Studios, has become one of the most recognized and imitated images in music history. Paul McCartney's barefoot appearance sparked the 'Paul is dead' conspiracy theory. The album features songs like 'Come Together,' 'Here Comes the Sun,' and the famous 'Abbey Road Medley.' The zebra crossing is now a Grade II listed site and remains a popular tourist destination.",
    citationUrl: "https://en.wikipedia.org/wiki/Abbey_Road",
    citationTitle: "Wikipedia: Abbey Road",
  },
  {
    text: "What is the smallest country in the world by area?",
    options: ["Monaco", "San Marino", "Vatican City", "Liechtenstein"],
    correctIndex: 2,
    category: "geography",
    difficulty: "medium",
    explanation: "Vatican City is just 0.44 km² (0.17 sq mi), surrounded by Rome.",
    detailedExplanation: "Vatican City (Stato della Città del Vaticano) is the world's smallest independent state, covering just 0.44 square kilometers (0.17 sq mi) with a population of about 800. It's an enclave within Rome, Italy, established as an independent state by the Lateran Treaty of 1929. The Pope serves as both head of the Catholic Church and sovereign of Vatican City. Notable landmarks include St. Peter's Basilica (the world's largest church), the Sistine Chapel with Michelangelo's famous ceiling, and the Vatican Museums housing one of the world's greatest art collections. Monaco (2.02 km²) is the second-smallest country, followed by San Marino (61 km²) and Liechtenstein (160 km²).",
    citationUrl: "https://en.wikipedia.org/wiki/Vatican_City",
    citationTitle: "Wikipedia: Vatican City",
  },
  {
    text: "Who developed the theory of relativity?",
    options: ["Isaac Newton", "Albert Einstein", "Stephen Hawking", "Niels Bohr"],
    correctIndex: 1,
    category: "science",
    difficulty: "easy",
    explanation: "Einstein published special relativity in 1905 and general relativity in 1915.",
    detailedExplanation: "Albert Einstein developed two theories of relativity that revolutionized our understanding of space, time, and gravity. Special relativity (1905) introduced the famous equation E=mc², showing that mass and energy are equivalent, and established that the speed of light is constant for all observers. General relativity (1915) described gravity not as a force but as the curvature of spacetime caused by mass and energy. These theories have been confirmed by numerous experiments and are fundamental to modern physics, GPS satellites, and our understanding of black holes. Einstein received the 1921 Nobel Prize in Physics, though for his work on the photoelectric effect rather than relativity.",
    citationUrl: "https://en.wikipedia.org/wiki/Theory_of_relativity",
    citationTitle: "Wikipedia: Theory of relativity",
  },
  {
    text: "What year did the Titanic sink?",
    options: ["1910", "1911", "1912", "1913"],
    correctIndex: 2,
    category: "history",
    difficulty: "medium",
    explanation: "The Titanic sank on April 15, 1912, hitting an iceberg on its maiden voyage.",
    detailedExplanation: "The RMS Titanic sank in the early morning of April 15, 1912, during her maiden voyage from Southampton to New York City. At the time, she was the largest ship afloat and was considered 'unsinkable' due to her advanced safety features. The ship struck an iceberg at 11:40 PM on April 14 and sank less than three hours later. Of the estimated 2,224 passengers and crew aboard, more than 1,500 died, making it one of the deadliest peacetime maritime disasters in history. The tragedy led to major improvements in maritime safety, including the establishment of the International Ice Patrol and new lifeboat requirements. The wreck was discovered in 1985 at a depth of about 3,800 meters.",
    citationUrl: "https://en.wikipedia.org/wiki/Titanic",
    citationTitle: "Wikipedia: Titanic",
  },
  {
    text: "Which sport uses the term 'love' to mean zero?",
    options: ["Golf", "Cricket", "Tennis", "Badminton"],
    correctIndex: 2,
    category: "sports",
    difficulty: "easy",
    explanation: "In tennis, 'love' means zero—possibly from the French 'l'œuf' (egg).",
    detailedExplanation: "In tennis, 'love' means a score of zero. The origin of this term is debated: the most popular theory suggests it comes from the French word 'l'œuf' (the egg), because a zero resembles an egg. Another theory proposes it comes from the Dutch 'lof' (honor) or from playing 'for love' (for nothing, without stakes). Tennis has a unique scoring system: points go 0 (love), 15, 30, 40, then game. A tie at 40-40 is called 'deuce,' requiring a two-point advantage to win the game. The sport originated in 12th-century France and modern lawn tennis developed in 19th-century England. The four Grand Slam tournaments are the Australian Open, French Open, Wimbledon, and US Open.",
    citationUrl: "https://en.wikipedia.org/wiki/Tennis_scoring_system",
    citationTitle: "Wikipedia: Tennis scoring system",
  },
  {
    text: "What is the longest river in the world?",
    options: ["Amazon", "Nile", "Yangtze", "Mississippi"],
    correctIndex: 1,
    category: "geography",
    difficulty: "medium",
    explanation: "The Nile is about 6,650 km long, flowing through 11 African countries.",
    detailedExplanation: "The Nile River is traditionally considered the world's longest river at approximately 6,650 km (4,130 miles), flowing through 11 countries in northeastern Africa from Lake Victoria to the Mediterranean Sea. Ancient Egypt's civilization flourished along its banks for thousands of years, dependent on its annual floods for agriculture. The river has two major tributaries: the White Nile (originating near Lake Victoria) and the Blue Nile (from Ethiopia), which meet in Khartoum, Sudan. The Amazon River is sometimes claimed as longer depending on how tributaries are measured, and it carries far more water—about 20% of all freshwater flowing into the world's oceans. The Yangtze (6,300 km) and Mississippi-Missouri (6,275 km) are the third and fourth longest.",
    citationUrl: "https://en.wikipedia.org/wiki/Nile",
    citationTitle: "Wikipedia: Nile",
  },
  {
    text: "Who wrote '1984'?",
    options: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"],
    correctIndex: 1,
    category: "literature",
    difficulty: "medium",
    explanation: "George Orwell published 1984 in 1949, introducing 'Big Brother' and 'doublethink.'",
    detailedExplanation: "George Orwell (pen name of Eric Arthur Blair) published '1984' in June 1949, just months before his death from tuberculosis. The dystopian novel depicts a totalitarian society under the all-seeing 'Big Brother,' where the 'Thought Police' punish independent thinking and history is continuously rewritten. Orwell coined terms that have become part of our vocabulary: 'Big Brother,' 'doublethink,' 'thoughtcrime,' 'Newspeak,' and 'Room 101.' The novel was partly inspired by Orwell's experiences of propaganda during WWII and his observations of Stalinism. Often compared to Aldous Huxley's 'Brave New World' (1932), the two books offer contrasting visions of dystopia—Orwell's through oppression, Huxley's through distraction and pleasure.",
    citationUrl: "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four",
    citationTitle: "Wikipedia: Nineteen Eighty-Four",
  },
  {
    text: "What is the main component of the Sun?",
    options: ["Helium", "Oxygen", "Hydrogen", "Carbon"],
    correctIndex: 2,
    category: "science",
    difficulty: "medium",
    explanation: "The Sun is about 73% hydrogen and 25% helium by mass.",
    detailedExplanation: "The Sun is composed of approximately 73% hydrogen and 25% helium by mass, with trace amounts of heavier elements like oxygen, carbon, neon, and iron. At its core, temperatures reach about 15 million degrees Celsius, enabling nuclear fusion where hydrogen atoms fuse to form helium, releasing enormous amounts of energy in the process. This fusion produces about 4 million tonnes of mass converted to energy every second via E=mc². The Sun has been burning for about 4.6 billion years and has enough hydrogen to continue for another 5 billion years. It's classified as a G-type main-sequence star (yellow dwarf) and contains 99.86% of all mass in our solar system.",
    citationUrl: "https://en.wikipedia.org/wiki/Sun",
    citationTitle: "Wikipedia: Sun",
  },
  {
    text: "Which country invented pizza?",
    options: ["Greece", "France", "Italy", "Spain"],
    correctIndex: 2,
    category: "general",
    difficulty: "easy",
    explanation: "Modern pizza originated in Naples, Italy, with the Margherita created in 1889.",
    detailedExplanation: "While flatbreads with toppings have existed for millennia across many cultures, modern pizza as we know it originated in Naples, Italy, in the 18th-19th centuries. The iconic Pizza Margherita was created in 1889 by pizzaiolo Raffaele Esposito to honor Queen Margherita of Italy, using tomatoes, mozzarella, and basil to represent the Italian flag's colors. Pizza remained largely a Neapolitan street food until Italian immigrants brought it to America in the late 19th century. After WWII, returning American soldiers spread its popularity, and pizza became a global phenomenon. Today, Neapolitan pizza-making is recognized by UNESCO as an Intangible Cultural Heritage. The world's largest pizza chain, Domino's, operates in over 90 countries.",
    citationUrl: "https://en.wikipedia.org/wiki/Pizza",
    citationTitle: "Wikipedia: Pizza",
  },
  {
    text: "What is the capital of Canada?",
    options: ["Toronto", "Vancouver", "Montreal", "Ottawa"],
    correctIndex: 3,
    category: "geography",
    difficulty: "medium",
    explanation: "Ottawa became Canada's capital in 1857, chosen by Queen Victoria.",
    detailedExplanation: "Ottawa was chosen as Canada's capital by Queen Victoria in 1857, a compromise between rival cities Montreal, Toronto, Kingston, and Quebec City. Its location on the border between Ontario and Quebec (English and French Canada) made it diplomatically suitable. Ottawa is Canada's fourth-largest city but serves as the political heart of the nation, home to Parliament Hill, the Supreme Court, and numerous embassies. The city sits at the confluence of three rivers: the Ottawa, Gatineau, and Rideau. The Rideau Canal, a UNESCO World Heritage Site, becomes the world's largest skating rink in winter. Toronto (population 2.9 million) is the largest city and financial capital, while Montreal and Vancouver are also major urban centers.",
    citationUrl: "https://en.wikipedia.org/wiki/Ottawa",
    citationTitle: "Wikipedia: Ottawa",
  },
  {
    text: "Who painted 'Starry Night'?",
    options: ["Claude Monet", "Vincent van Gogh", "Pablo Picasso", "Salvador Dalí"],
    correctIndex: 1,
    category: "arts",
    difficulty: "easy",
    explanation: "Van Gogh painted Starry Night in 1889 while at an asylum in France.",
    detailedExplanation: "Vincent van Gogh painted 'The Starry Night' in June 1889 while staying at the Saint-Paul-de-Mausole asylum in Saint-Rémy-de-Provence, France, where he had admitted himself following a mental breakdown. The painting depicts a swirling night sky over a village, with a prominent cypress tree and a church spire. Van Gogh created the piece from memory during the day, as he painted his night scenes indoors. Though now considered one of the most recognized paintings in Western art, Van Gogh himself was not particularly pleased with it. He sold only one painting during his lifetime before dying at age 37 in 1890. 'Starry Night' now hangs in the Museum of Modern Art in New York City.",
    citationUrl: "https://en.wikipedia.org/wiki/The_Starry_Night",
    citationTitle: "Wikipedia: The Starry Night",
  },
  {
    text: "What is the hardest natural substance on Earth?",
    options: ["Gold", "Iron", "Diamond", "Titanium"],
    correctIndex: 2,
    category: "science",
    difficulty: "easy",
    explanation: "Diamond scores 10 on the Mohs hardness scale, the maximum.",
    detailedExplanation: "Diamond is the hardest naturally occurring substance on Earth, scoring 10 on the Mohs hardness scale (the maximum). Diamonds are made of carbon atoms arranged in a crystal structure called a diamond cubic lattice, where each carbon atom is bonded to four others in a tetrahedral arrangement. This structure forms under extreme conditions: temperatures above 1,050°C and pressures of 45-60 kilobars, typically 150-200 km below Earth's surface. Natural diamonds are brought to the surface through volcanic eruptions in kimberlite pipes. While diamond is extremely hard (resistant to scratching), it is not the toughest material—it can shatter under impact. About 80% of mined diamonds are used industrially for cutting, drilling, and grinding.",
    citationUrl: "https://en.wikipedia.org/wiki/Diamond",
    citationTitle: "Wikipedia: Diamond",
  },
  {
    text: "In which year did the Berlin Wall fall?",
    options: ["1987", "1988", "1989", "1990"],
    correctIndex: 2,
    category: "history",
    difficulty: "medium",
    explanation: "The Berlin Wall fell on November 9, 1989, symbolizing the end of the Cold War.",
    detailedExplanation: "The Berlin Wall fell on November 9, 1989, after an East German government spokesman mistakenly announced that border restrictions were lifted 'immediately.' Thousands of East Berliners rushed to crossing points, and overwhelmed guards eventually opened the gates. People from both sides began dismantling the wall with hammers and picks. The wall had stood since August 13, 1961, built by the East German government to prevent citizens from fleeing to the West. During its 28-year existence, at least 140 people died attempting to cross. The fall of the wall led to German reunification on October 3, 1990, and marked a symbolic end to the Cold War. Sections of the wall are now preserved as memorials, and 'Mauerspechte' (wall woodpeckers) sold pieces as souvenirs.",
    citationUrl: "https://en.wikipedia.org/wiki/Fall_of_the_Berlin_Wall",
    citationTitle: "Wikipedia: Fall of the Berlin Wall",
  },
  {
    text: "What is the largest desert in the world?",
    options: ["Sahara", "Arabian", "Gobi", "Antarctic"],
    correctIndex: 3,
    category: "geography",
    difficulty: "hard",
    explanation: "Antarctica is the largest desert—deserts are defined by precipitation, not heat!",
    detailedExplanation: "The Antarctic Desert is the largest desert in the world at approximately 14.2 million km², followed closely by the Arctic Desert. Deserts are defined by precipitation (less than 250mm annually), not temperature—so polar deserts qualify. Antarctica receives less than 51mm of precipitation annually in its interior, making it the driest continent on Earth. The Sahara (9.2 million km²) is the largest hot desert and what most people picture when they think of deserts. The Arabian Desert (2.3 million km²) and Gobi Desert (1.3 million km²) are also significant. Antarctica's extreme cold means any snow that falls rarely melts, instead compressing into the ice sheets that contain 70% of Earth's fresh water.",
    citationUrl: "https://en.wikipedia.org/wiki/Antarctic_Desert",
    citationTitle: "Wikipedia: Antarctic Desert",
  },
  {
    text: "Who directed 'Jurassic Park'?",
    options: ["James Cameron", "Steven Spielberg", "George Lucas", "Ridley Scott"],
    correctIndex: 1,
    category: "entertainment",
    difficulty: "medium",
    explanation: "Spielberg directed Jurassic Park (1993), revolutionizing CGI in cinema.",
    detailedExplanation: "Steven Spielberg directed Jurassic Park, released in 1993, based on Michael Crichton's 1990 novel. The film revolutionized visual effects by pioneering the use of computer-generated imagery (CGI) for living creatures, combined with Stan Winston's animatronic dinosaurs. It became the highest-grossing film of all time upon release, earning over $1 billion worldwide. The movie's blend of CGI and practical effects set new standards for blockbuster filmmaking. Spielberg, already famous for Jaws (1975), E.T. (1982), and the Indiana Jones series, won Best Director Oscars for Schindler's List (1993) and Saving Private Ryan (1998). The Jurassic franchise has since spawned five sequels and remains a cultural phenomenon.",
    citationUrl: "https://en.wikipedia.org/wiki/Jurassic_Park_(film)",
    citationTitle: "Wikipedia: Jurassic Park (film)",
  },
  {
    text: "What is the speed of light in a vacuum?",
    options: ["300,000 km/s", "150,000 km/s", "500,000 km/s", "100,000 km/s"],
    correctIndex: 0,
    category: "science",
    difficulty: "hard",
    explanation: "Light travels at ~299,792 km/s—nothing with mass can travel this fast.",
    detailedExplanation: "The speed of light in a vacuum is exactly 299,792,458 meters per second (approximately 300,000 km/s or 186,000 miles/s). This is denoted by the letter 'c' and is a fundamental constant of nature. According to Einstein's special relativity, 'c' is the cosmic speed limit—nothing with mass can reach or exceed it. As objects approach the speed of light, their relativistic mass increases infinitely, requiring infinite energy to accelerate further. Light takes about 8 minutes to travel from the Sun to Earth, and about 4.24 years to reach us from the nearest star, Proxima Centauri. In other media like water or glass, light travels slower due to interactions with atoms, creating effects like refraction.",
    citationUrl: "https://en.wikipedia.org/wiki/Speed_of_light",
    citationTitle: "Wikipedia: Speed of light",
  },
  {
    text: "Which instrument has 88 keys?",
    options: ["Guitar", "Violin", "Piano", "Organ"],
    correctIndex: 2,
    category: "arts",
    difficulty: "easy",
    explanation: "A standard piano has 88 keys: 52 white and 36 black.",
    detailedExplanation: "A standard modern piano has 88 keys: 52 white keys and 36 black keys, spanning 7¼ octaves from A0 (27.5 Hz) to C8 (4,186 Hz). This range was standardized in the late 19th century by Steinway and has become the international standard. Earlier pianos had fewer keys—Mozart's pianos had only 5 octaves. The piano was invented around 1700 by Bartolomeo Cristofori in Italy, originally called 'pianoforte' (soft-loud) because unlike the harpsichord, it could play at different volumes. The piano works by hammers striking strings when keys are pressed. Some extended pianos, like the Bösendorfer Imperial, have 97 keys.",
    citationUrl: "https://en.wikipedia.org/wiki/Piano",
    citationTitle: "Wikipedia: Piano",
  },
  {
    text: "What is the smallest prime number?",
    options: ["0", "1", "2", "3"],
    correctIndex: 2,
    category: "science",
    difficulty: "medium",
    explanation: "2 is the smallest and only even prime number.",
    detailedExplanation: "2 is the smallest prime number and the only even prime. A prime number is defined as a natural number greater than 1 that has exactly two distinct positive divisors: 1 and itself. This is why 1 is not prime—it only has one divisor (itself). 0 is also not prime as it's divisible by every number. Every even number greater than 2 is divisible by 2, so 2 is the only even prime. Prime numbers are fundamental in mathematics and are the building blocks of all natural numbers through the Fundamental Theorem of Arithmetic. They're also crucial in modern cryptography—RSA encryption relies on the difficulty of factoring large products of primes.",
    citationUrl: "https://en.wikipedia.org/wiki/Prime_number",
    citationTitle: "Wikipedia: Prime number",
  },
  {
    text: "Who wrote 'The Great Gatsby'?",
    options: ["Ernest Hemingway", "F. Scott Fitzgerald", "John Steinbeck", "William Faulkner"],
    correctIndex: 1,
    category: "literature",
    difficulty: "medium",
    explanation: "F. Scott Fitzgerald published The Great Gatsby in 1925.",
    detailedExplanation: "F. Scott Fitzgerald published 'The Great Gatsby' in 1925, though it received mixed reviews and modest sales during his lifetime. Set on Long Island's North Shore during the summer of 1922, the novel explores themes of decadence, idealism, social upheaval, and the corrupting nature of wealth during the Jazz Age. The story is narrated by Nick Carraway, who becomes entangled with his mysterious neighbor Jay Gatsby and Gatsby's obsession with Nick's cousin Daisy Buchanan. The novel is now considered a masterpiece of American literature and is required reading in many schools. Fitzgerald died in 1940 believing himself a failure; the book's popularity surged during WWII when it was distributed to American soldiers.",
    citationUrl: "https://en.wikipedia.org/wiki/The_Great_Gatsby",
    citationTitle: "Wikipedia: The Great Gatsby",
  },
  {
    text: "What is the national animal of Australia?",
    options: ["Koala", "Kangaroo", "Platypus", "Wombat"],
    correctIndex: 1,
    category: "general",
    difficulty: "easy",
    explanation: "The kangaroo appears on Australia's coat of arms alongside the emu.",
    detailedExplanation: "The kangaroo is one of Australia's national animals, appearing on the Commonwealth Coat of Arms alongside the emu. Both animals were chosen because they cannot easily walk backward, symbolizing a nation always moving forward. There are four main species of kangaroo: the red kangaroo (the largest marsupial), the eastern grey, western grey, and antilopine kangaroo. Red kangaroos can leap up to 9 meters in a single bound and reach speeds of 56 km/h. Kangaroos are found only in Australia and are so numerous (around 50 million) that they significantly outnumber the human population. The term 'kangaroo' likely comes from the Guugu Yimithirr word 'gangurru.'",
    citationUrl: "https://en.wikipedia.org/wiki/Kangaroo",
    citationTitle: "Wikipedia: Kangaroo",
  },
  {
    text: "Which planet has the most moons?",
    options: ["Jupiter", "Saturn", "Uranus", "Neptune"],
    correctIndex: 1,
    category: "science",
    difficulty: "hard",
    explanation: "Saturn leads with 146 confirmed moons, surpassing Jupiter's 95.",
    detailedExplanation: "As of 2023, Saturn has the most confirmed moons with 146, overtaking Jupiter which has 95. Saturn's moons include Titan (larger than Mercury and the only moon with a dense atmosphere), Enceladus (which has liquid water geysers), and Rhea. Jupiter's moons include Ganymede (the largest moon in our solar system), Europa (with a subsurface ocean that may harbor life), volcanic Io, and cratered Callisto. Uranus has 28 moons and Neptune has 16, with Triton being its largest. The moon count continues to change as new discoveries are made—Saturn gained 62 new moons in 2023 alone. Most of these newly discovered moons are small, irregular satellites just a few kilometers across.",
    citationUrl: "https://en.wikipedia.org/wiki/Moons_of_Saturn",
    citationTitle: "Wikipedia: Moons of Saturn",
  },
  {
    text: "What year was the first iPhone released?",
    options: ["2005", "2006", "2007", "2008"],
    correctIndex: 2,
    category: "general",
    difficulty: "medium",
    explanation: "Steve Jobs unveiled the first iPhone on January 9, 2007.",
    detailedExplanation: "Steve Jobs unveiled the first iPhone at Macworld Conference & Expo on January 9, 2007, calling it 'a revolutionary product that changes everything.' The iPhone went on sale June 29, 2007, with people camping outside Apple Stores for days. It combined three devices into one: a widescreen iPod, a mobile phone, and an internet communications device. The original iPhone had a 3.5-inch display, 2-megapixel camera, and no App Store (that came in 2008 with iPhone 3G). It was initially exclusive to AT&T in the US and cost $499/$599 for 4GB/8GB. The iPhone fundamentally changed the smartphone industry, leading to the decline of Nokia and BlackBerry and establishing the modern touchscreen smartphone paradigm.",
    citationUrl: "https://en.wikipedia.org/wiki/IPhone_(1st_generation)",
    citationTitle: "Wikipedia: iPhone (1st generation)",
  },
  {
    text: "Who is known as the 'Father of Computers'?",
    options: ["Alan Turing", "Charles Babbage", "Bill Gates", "Steve Jobs"],
    correctIndex: 1,
    category: "science",
    difficulty: "medium",
    explanation: "Charles Babbage designed the first mechanical computer in the 1820s.",
    detailedExplanation: "Charles Babbage (1791-1871) is known as the 'Father of the Computer' for his pioneering work on mechanical computing. In the 1820s, he designed the Difference Engine to calculate polynomial functions and print mathematical tables. He later conceived the Analytical Engine, which contained concepts foundational to modern computing: a central processing unit (the 'mill'), memory (the 'store'), and the ability to be programmed using punched cards. Ada Lovelace, who worked with Babbage, wrote what is considered the first computer algorithm. Though neither machine was completed in his lifetime due to funding issues and manufacturing limitations, Babbage's designs proved sound when the Difference Engine was built in 1991 at London's Science Museum.",
    citationUrl: "https://en.wikipedia.org/wiki/Charles_Babbage",
    citationTitle: "Wikipedia: Charles Babbage",
  },
  {
    text: "What is the capital of Brazil?",
    options: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"],
    correctIndex: 2,
    category: "geography",
    difficulty: "medium",
    explanation: "Brasília became Brazil's capital in 1960, replacing Rio de Janeiro.",
    detailedExplanation: "Brasília became Brazil's capital on April 21, 1960, replacing Rio de Janeiro as part of President Juscelino Kubitschek's plan to develop Brazil's interior. The city was built in just 41 months and designed by urban planner Lúcio Costa and architect Oscar Niemeyer in the modernist style. From above, the city's layout resembles an airplane or bird. Brasília was designated a UNESCO World Heritage Site in 1987 for its innovative urban planning and modernist architecture. Despite being the capital, it's only Brazil's third-largest city—São Paulo (12 million) and Rio de Janeiro (6.7 million) are larger. Rio was the capital from 1763-1960, and Salvador was the first capital from 1549-1763.",
    citationUrl: "https://en.wikipedia.org/wiki/Bras%C3%ADlia",
    citationTitle: "Wikipedia: Brasília",
  },
  {
    text: "Which Shakespeare play features the character Hamlet?",
    options: ["Macbeth", "Othello", "Hamlet", "King Lear"],
    correctIndex: 2,
    category: "literature",
    difficulty: "easy",
    explanation: "Hamlet appears in the play 'Hamlet,' written around 1600.",
    detailedExplanation: "Hamlet is the protagonist of Shakespeare's tragedy 'Hamlet,' written around 1600-1601. Prince Hamlet seeks revenge against his uncle Claudius, who murdered Hamlet's father, took the throne of Denmark, and married Hamlet's mother Gertrude. The play contains some of Shakespeare's most famous lines: 'To be, or not to be' (the opening of the 'nunnery scene' soliloquy), 'Something is rotten in the state of Denmark,' and 'Alas, poor Yorick!' It's Shakespeare's longest play at about 4,000 lines and has been adapted into films starring Laurence Olivier, Kenneth Branagh, and Mel Gibson. The character Hamlet is considered one of the most complex in Western literature.",
    citationUrl: "https://en.wikipedia.org/wiki/Hamlet",
    citationTitle: "Wikipedia: Hamlet",
  },
  {
    text: "What is the boiling point of water at sea level in Celsius?",
    options: ["90°C", "100°C", "110°C", "120°C"],
    correctIndex: 1,
    category: "science",
    difficulty: "easy",
    explanation: "Water boils at 100°C (212°F) at sea level.",
    detailedExplanation: "Water boils at 100°C (212°F) at standard atmospheric pressure at sea level. The Celsius scale was originally defined by this boiling point (100°) and the freezing point of water (0°). Boiling occurs when the water's vapor pressure equals atmospheric pressure, allowing bubbles to form throughout the liquid. At higher altitudes where air pressure is lower, water boils at lower temperatures—at the top of Mount Everest, water boils at only 70°C. This is why cooking takes longer at high altitudes. Conversely, pressure cookers raise the boiling point by increasing pressure, cooking food faster. Pure water at standard conditions transitions directly between liquid and gas states at exactly 99.9839°C.",
    citationUrl: "https://en.wikipedia.org/wiki/Boiling_point",
    citationTitle: "Wikipedia: Boiling point",
  },
  {
    text: "Which country hosted the 2016 Summer Olympics?",
    options: ["China", "UK", "Brazil", "Japan"],
    correctIndex: 2,
    category: "sports",
    difficulty: "medium",
    explanation: "Brazil hosted the 2016 Rio Olympics—the first in South America.",
    detailedExplanation: "Brazil hosted the 2016 Summer Olympics in Rio de Janeiro, making it the first South American nation to host the Games. The Olympics took place from August 5-21, 2016, featuring 11,238 athletes from 207 nations competing in 306 events. Memorable moments included Usain Bolt completing his 'triple-triple' (three golds in three consecutive Olympics in 100m, 200m, and 4x100m), Michael Phelps winning his 23rd career gold medal, Simone Biles dominating gymnastics with four gold medals, and host nation Brazil winning its first-ever Olympic gold in men's football. The Games faced challenges including Zika virus concerns and Rio's economic struggles. China hosted in 2008 (Beijing), the UK in 2012 (London), and Japan hosted in 2021 (Tokyo, delayed from 2020).",
    citationUrl: "https://en.wikipedia.org/wiki/2016_Summer_Olympics",
    citationTitle: "Wikipedia: 2016 Summer Olympics",
  },
];

// Shuffle array using Fisher-Yates algorithm
function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

export function getMockQuestions(count: number): Question[] {
  const shuffled = shuffleArray(questionBank);
  return shuffled.slice(0, count).map((q) => ({
    ...q,
    id: uuidv4(),
  }));
}
